{{- if and (not .Values.rabbitmq.enabled) (not .Values.externalRabbitmq.existingSecret) (not .Values.rabbitmq.existingSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "common.names.fullname" .) "rabbitmq" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.externalRabbitmq.password | b64enc | quote }}
{{- end }}
