apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-worker" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- include "app.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: {{ include "app.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["node", "dist/worker.js"]
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- include "app.configure.postgresql" . | nindent 12 }}
            {{- include "app.configure.redis" . | nindent 12 }}
            {{- include "app.configure.meilisearch" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "common.names.fullname" . | quote }}
                optional: true
